/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fae05f14-cdac-4cbb-ae02-80e130ce02ea",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0CAlPPUJ9",
    "aws_user_pools_web_client_id": "4chr36d34rgsl6uu4aurc5fhs6",
    "oauth": {},
    "aws_content_delivery_bucket": "ircocom-20200924223736-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1y15trwqltue4.cloudfront.net"
};


export default awsmobile;
